apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-bg-green
  namespace: bg
  labels:
    app: app-bg
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-bg
      version: green
  template:
    metadata:
      labels:
        app: app-bg
        version: green
    spec:
      initContainers:
      - name: render
        image: busybox:1.37
        command:
        - sh
        - -c
        - sed "s/{{COLOR}}/GRENN/" /tmp/in/index.html > /tmp/out/index.html
        volumeMounts:
        - name: html-src
          mountPath: /tmp/in
        - name: html
          mountPath: /tmp/out
      containers:
      - name: web
        image: nginx:1.25.5
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: html-src
        configMap:
          name: app-bg-html
      - name: html
        emptyDir: {}
