apiVersion: v1
kind: Service
metadata:
  name: app-rollout
  namespace: rollout
spec:
  type: NodePort
  selector:
    app: app-rollout
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30095
